### ISSUE TITLE
Max pages = 10, hiding old posts

### ISSUE THREAD

**Issue by stephlocke** [curtistimson/hugo-theme-massively#23]
Ideally, a shifting behaviour of visibility of pages available to select in the paginator code would be great. In the interim, a higher page limit and guidance to up the number of posts per page on the README would be a quick win.

**Comment by stephlocke** [comment]
The default of 10 items to a page makes sense but the limit of 10 pages does not - I didn't want to substantially alter your code for this so I just upped the max. However, this is still brittle and it'd be better to have functionality like many paginator navs which show the page numbers within x dist of the current page number so you can have infinite pages.

**Comment by curttimson** [comment]
@stephlocke Apologies I misunderstood! I see what you mean now. There is an overall limit to the number of pages allowed, so old posts will not be accessible.

**Comment by curttimson** [comment]
@stephlocke Looking at the code a second time it looks as though only the pagination in between the "Previous" and "Next" links would be hidden if there are more than 10 pages.

For example if there were 150 pages, page 129 & 131 would be accessible from page 130.

I think a better fix than increasing the limit to 15 would be to display the previous 4 and next 4 pages depending on which page you were on.

For example page 130 would show:

 - Previous
 - 126
 - 127
 - 128
 - 129
 - 130
 - 131
 - 132
 - 133
 - 134
 - Next

Thoughts?

**Comment by stephlocke** [comment]
Agreed - this would be much better for everyone

**Comment by Urm3l** [comment]
I fixed the issue as @curtistimson suggested and created a PR

**Comment by curtistimson** [comment]
Fixed as part of #58
